#!/bin/bash

RED=$(tput setaf 1)
GREEN=$(tput setaf 2)
YELLOW=$(tput setaf 3)
COLOR_RESET=$(tput sgr0)

say() {
  echo -e "${2:-$YELLOW}$1${COLOR_RESET}"
}

error_check() {
  if [ $? -ne 0 ]; then
    say "$1" $RED
    exit $?
  fi
}

command_exists() {
  type "$1" &> /dev/null;
}

if ! command_exists brew; then
  say "Installing Hombrew"
  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

say "Installing needed Hombrew packages"
brew install git zsh tmux vim stow

say "Getting onehouse dotfiles"
git clone git@github.com:onehouse/dotfiles.git onehouse-dotfiles
error_check "Problem downloading dotfiles"
cd onehouse-dotfiles

say "Setting up dotfiles"
stow vim zsh rubygems tmux git
touch ~/.zshrc.local
cp templates/.gitconfig ~/

say "Installing tmux plugin manager"
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
tmux source ~/.tmux.conf
~/.tmux/plugins/tpm/scripts/install_plugins.sh

say "Setting up utility scripts"
mkdir -p ~/bin
ln -s ~/onehouse-dotfiles/bin/* ~/bin/
