# Misc
alias v='vim'
alias retag='ctags -R --exclude=.git --exclude=log --exclude=tmp --exclude=.js'
alias va='vagrant'
alias l='ls -hla'
alias la='ls -hal'
alias u='cd .. && ls -lha'
alias s='ssh'
alias pjson='python -mjson.tool'
alias sourcedots='source ~/elliot-larson-dotfiles/zsh/.oh-my-zsh/custom/*'
alias edithosts='sudo vi /etc/hosts'
alias reloadhosts='dscacheutil -flushcache; sudo killall -HUP mDNSResponder'
alias npr='npm run -s'
alias co='code .'

# Ruby
alias b='bundle'
alias bi='bundle install'
alias bu='bundle update'
alias be='bundle exec'
alias bo='bundle open'
alias bs='bundle show'
alias bake='bundle exec rake'
alias bspec='bundle exec rspec'
alias bspecs='bundle exec rspec spec'
alias rps='rake parallel:spec'
alias rpp='rake parallel:prepare'
alias rdm='rake db:migrate'
alias rdt='rake db:migrate db:test:prepare'
alias r='rails'
alias z='zeus'
alias zake='zeus rake'
alias zspec='zeus rspec'
alias zs='zeus start'
alias zr='zeus rspec'
alias zc='zeus console'
alias mm='middleman'

# python
alias py='python'
alias pyp='python -m pip'
alias pypi='python -m pip install'
alias pyt='pytest'
alias pytv='pytest -v'
alias ipy='ipython'
alias dj='python manage.py'
alias djs='python manage.py runserver'
alias djmm='python manage.py makemigrations'
alias djm='python manage.py migrate'
alias djld='python manage.py loaddata'

# Git
alias g='git'
alias ga='git add'
alias gadd='git add'
alias gA='git add -A'
alias gd='git diff'
alias gds='dit diff --staged'
alias gs='git status'
alias gl='git log'
alias glp='git log -p'
alias glop='git log -p'
alias glpp='git log --pretty=format:"%C(yellow)%h%C(reset) %C(blue)%ci%C(reset) %s %C(blue)[%cn]%C(reset)"'
alias gf='git fetch'
alias gush='git push'
alias gull='git pull'
alias gech='git fetch'
alias gone='git clone'
alias gout='git checkout'
alias goub='git checkout -b'
alias gaco='git add -A && git commit -m'
alias gset='git reset'
alias gase='git rebase'
alias gasec='git rebase --continue'
alias gash='git stash -u'
alias gpop='git stash pop'
alias giff='git diff'
alias gerg='git merge'
alias gac='git add -A && git commit'
alias gm='git merge'
alias gr='git reset'
alias gcm='git commit -m'
alias gc='git commit'

# Tmux
alias t='tmux'
alias tl='tmux ls'
alias tn='tmux new -s'
alias ta='tmux attach -t'
alias taa='tmux attach'
alias tk='tmux kill-session -t'
alias tka='tmux kill-server'
alias tka='tmux kill-server'
alias rmux='railsmux'
alias tnr='railsmux'
