alias home="cl ~/ "
alias desktop="cl ~/Desktop "
alias downloads="cl ~/Downloads "
alias dropbox="cl ~/Dropbox"
alias work="cl ~/Work"
alias dots="cl ~/dotfiles"
alias documents="cl ~/Documents"
alias docs="cl ~/Documents"
